# MINIMESSAGE 的 hover 等语法不支持在 lore 中使用
# 槽位一定要限制：不然会出现玩家双手武器伤害和效果都能生效的问题

NBT全知全能:
  id: book
  display_name: "<red>NBT组件测试"
  custom_model_data: 10086
  dyed_color: 0xFF5500
  lore:
    - "<red>所有支持的组件都来一套"
    - "<yellow>全是bug :("
  max_stack_size: 1
  attribute:
    random_id_1:
      attr: ATTACK_DAMAGE
      amount: 5.0
      operation: add_value
      slot: offhand
    random_id_2:
      attr: ATTACK_KNOCKBACK
      amount: 0.2
      operation: add_value
      slot: mainhand
  shield:
    delay_seconds: 0
    base: 1
    factor: 0.5
    threshold: 90
    pass: arrow
    cooldown_scale: 1
    reduction:  # 未指定能阻挡一切伤害
      random_key:
        base: 4
        factor: 0.5
        angle: 180
        type: is_player_attack
    block_sound:
      id: block.campfire.crackle
      range: 8
    disable_sound:
      id: block.end_portal.spawn
      range: 16
  break_sound:
    id: block.end_portal_frame.fill
    range: 16
  consumable:
    animation: eat
    consume_seconds: 5
    particle: true
    sound:
      id: block.anvil.land
      range: 16
    effects:
      apply_effects:
        chance: 0.5
        potions:
          slowness:
            duration: 200
            amplifier: 2
            icon: false
            particles: true
  ori_durability:
    damage: 50
    max_damage: 51
    unbreakable: false
  resistant: is_fire
  death_protection:
    apply_effects:  # apply_effects,play_sound,remove_effects,clear_all_effects,teleport_randomly
      chance: 0.5
      potions:
        slowness:
          duration: 200
          amplifier: 2
          icon: false
          particles: true
  enchant:
    value: 90
    enchants:
      - "sharpness 3"
      - "unbreaking 2"
  glint: true
  equippable:
    allow:
      - player
      - zombie
    # asset: 装备模型命名空间ID
    # camera: 纹理命名空间ID   例子：带上南瓜头的玩家视角纹理
    can_shear: true
    damage_on_hurt: true
    equip_on_interact: true
    equip_sound:
      id: bucket.empty_water
      range: 16
    dispensable:
    shearing_sound:
      id: bottle.dragonbreath
    slot: head
    swappable: true
  food:
    always_eat: true     # 是否可随时食用（无视饱食度）
    nutrition: 8          # 饱食度
    saturation: 0.6       # 饱和
  glider:  # 写了就行, 无视值
  # 可播放组件
  music_disc: cat  # 唱片机曲目命名空间ID
  # 药水效果
  potion:
    color: "#FF0000"
    name: "强效治疗药水"
    id: minecraft:healing
    duration_scale: 1.5
    potions:
      regeneration:
        duration: 600
        amplifier: 2
      absorption:
        duration: 300
        amplifier: 1
  rarity: epic  # COMMON,UNCOMMON,RARE,EPIC,
  repair:
    cost: 10 # 累计惩罚值
    items:
      - stone
  tool:
    creative_destroy: false
    damage_per_block: 10
    default_speed: 0.1
    rules:
      random_key:
        items:
          - minecraft:bedrock
          - minecraft:stone
        drop: true
        speed: 8.0
  tooltip:
    hide_tooltip: false  # 不隐藏提示框
    hide_tags:  # 1.20.5之后写组件名，之前写hide_flags中的值
      - attribute_modifiers
    # style: 物品提示框外观命名空间id
  use_cooldown:
    group: terra_group_1  # 同组物品的冷却共享
    seconds: 5
  use_remainder:
    id: axolotl_bucket
    component: "{\"minecraft:custom_name\":\"??\"}"  # 正常格式：{minecraft:custom_name:'{"color":"yellow","text":"打咩哟"}'}  # 所有组件一定要有minecraft:！！！！
    count: 1
  weapon:
    disable_shield_seconds: 5
    damage_per_attack: 2

谢版盾牌:
  id: feather
  display_name: "<red>NBT盾牌(额外)测试"
  max_stack_size: 1
  shield:
    delay_seconds: 0
    base: 7
    factor: 0.5
    threshold: 5
    pass: arrow
    cooldown_scale: 1
    reduction:  # 未指定能阻挡一切伤害
      random_key:
        base: 4
        factor: 0.5
        angle: 180
    block_sound:
      id: block.campfire.crackle
      range: 8
    disable_sound:
      id: block.end_portal.spawn
      range: 16
  break_sound:
    id: block.end_portal_frame.fill
    range: 16
  resistant: is_fire
  rarity: epic  # COMMON,UNCOMMON,RARE,EPIC,

头盔耐久测试:
  id: iron_helmet
  display_name: "<yellow>头盔耐久测试"
  lore:
    - "<blue>耐久值:{terra_durability}"
  max_stack_size: 1
  terra_durability:
    damage: 0
    max_damage: 10
    break_loss: true
  glint: true

胸甲耐久测试:
  id: iron_chestplate
  display_name: "<yellow>胸甲耐久测试"
  lore:
    - "<blue>耐久值:{terra_durability}"
  max_stack_size: 1
  terra_durability:
    damage: 0
    max_damage: 10
    break_loss: true
  glint: true

护腿耐久测试:
  id: iron_leggings
  display_name: "<yellow>护腿耐久测试"
  lore:
    - "<blue>耐久值:{terra_durability}"
  max_stack_size: 1
  terra_durability:
    damage: 0
    max_damage: 10
    break_loss: true
  glint: true

靴子耐久测试:
  id: iron_boots
  display_name: "<yellow>靴子耐久测试"
  lore:
    - "<blue>耐久值:{terra_durability}"
  max_stack_size: 1
  terra_durability:
    damage: 0
    max_damage: 10
    break_loss: true
  glint: true

工具耐久测试:
  id: wooden_axe
  display_name: "<yellow>工具耐久测试"
  lore:
    - "<blue>耐久值:{terra_durability}"
  max_stack_size: 1
  terra_durability:
    damage: 0
    max_damage: 10
    break_loss: true
  tool:
    creative_destroy: false
    damage_per_block: 10 # 本插件支持识别
    default_speed: 0.1
    rules:
      random_key:
        items:
          - minecraft:bedrock
          - minecraft:stone
        drop: true
        speed: 8.0
  glint: true

钓竿耐久测试:
  id: fishing_rod
  display_name: "<yellow>工具耐久测试"
  lore:
    - "<gray>我还支持原版的break_sound :)"
    - "<blue>耐久值:{terra_durability}"
  max_stack_size: 1
  terra_durability:
    damage: 0
    max_damage: 10
    break_loss: true
  glint: true
  break_sound: # terra_durability也支持原版的break_sound指令，range无效
    id: block.anvil.land

武器耐久测试:
  id: golden_sword
  display_name: "<yellow>武器耐久测试"
  lore:
    - "<gradient:#FFD700:#8B4513>你的升级之路必定艰难()</gradient>"
    - "<red>玻璃大炮</red>"
    - "<gray>用升级材料即可, 没错就是我懒得写了</gray>"
    - "<blue>耐久值:{terra_durability}"
  max_stack_size: 1
  terra_durability:
    damage: 0
    max_damage: 125
    break_loss: false
    # 支持java的Math库，damage-目前的损伤值  max_damage 此物品最大损伤值  harm-武器或护甲则表示造成或承受的伤害，钓竿，弓，弩的值为0
    damage_per_use_expr: "Math.max(1, harm * (damage / max_damage + 1))"
  glint: true
  weapon:
    damage_per_attack: 5  # 本插件支持识别，三叉戟也支持

弓耐久测试:
  id: bow
  display_name: "<yellow>弓耐久测试"
  lore:
    - "<blue>耐久值:{terra_durability}"
  max_stack_size: 1
  terra_durability:
    damage: 0
    max_damage: 9
    break_loss: false
  glint: true
  break_sound: # terra_durability也支持原版的break_sound指令，range无效
    id: block.wooden_door.open

弩耐久测试:
  id: crossbow
  display_name: "<yellow>弩耐久测试"
  lore:
    - "<blue>耐久值:{terra_durability}"
  max_stack_size: 1
  terra_durability:
    damage: 0
    max_damage: 9
    break_loss: false
  glint: true